name: GuardDog npm Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  guarddog:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Scan npm dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install GuardDog
        run: pip install guarddog

      - name: Find package.json files
        id: find-package-json
        run: |
          echo "files=$(find . -name 'package.json' -not -path '*/node_modules/*' -type f | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Scan package.json files
        run: |
          mkdir -p scan-results
          for pkg in ${{ steps.find-package-json.outputs.files }}; do
            echo "Scanning $pkg..."
            guarddog npm verify "$pkg" --output-format sarif > "scan-results/$(basename $(dirname $pkg))-guarddog.sarif"
          done

      - name: Upload SARIF files to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: guarddog-npm
          sarif_file: scan-results 
